### ISSUE TITLE
Native extensions fail to build on FreeBSD 11.0

### ISSUE THREAD

**Issue by duncan-bayne** [tobijk/libarchive-ruby-swig#4]
On the following system: `FreeBSD freebsd-test 11.0-RELEASE-p1 FreeBSD 11.0-RELEASE-p1 #0 r306420: Thu Sep 29 01:43:23 UTC 2016     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64`

... I run `gem install libarchive-ruby-swig` and it fails with:

```
current directory: /usr/home/duncan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/libarchive-ruby-swig-0.6.3/ext/libarchive-ruby-swig
make "DESTDIR="
compiling libarchive_wrap.cxx
g++: error: unrecognized command line option '-Wshorten-64-to-32'
g++: error: unrecognized command line option '-Wdivision-by-zero'
g++: error: unrecognized command line option '-Wextra-tokens'
*** Error code 1

Stop.
make: stopped in /usr/home/duncan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/libarchive-ruby-swig-0.6.3/ext/libarchive-ruby-swig

make failed, exit code 1
```
Looks like it's passing compiler options that clang doesn't understand.

**Comment by tobijk** [comment]
The gem itself does not set any build options. The makefile is generated by Ruby's own build system.

On another note I just tried a `clang++ -Wshorten-64-to-32 test.cpp` on my system and there was no error, but when calling `g++ -Wshorten-64-to-32 test.cpp` I get the error above. So I think what's happening here is that Ruby detects clang and sets the CFLAGS accordingly, but then it uses gcc during build instead.

Add these two lines

    RbConfig::MAKEFILE_CONFIG['CC']  = ENV['CC']  if ENV['CC']
    RbConfig::MAKEFILE_CONFIG['CXX'] = ENV['CXX'] if ENV['CXX']

at the top of `ext/libarchive-ruby-swig/extconf.rb` after the requires. Then explicitly set the path to CC and CXX via something like

    export CC=`which clang`
    export CXX=`which clang++`

Then do `rake clean` and `rake build`. Hope that helps.

**Comment by duncan-bayne** [comment]
Hmmm.  That sounds like a bug in the Ruby build system itself.  Shall I file it, or would you prefer to?  It feels slightly odd doing it myself as it's not my Gem that's going bang :)

**Comment by tobijk** [comment]
Before filing a bug against anything, you need to properly investigate and narrow down the problem. I just took a guess here. Neither do I run FreeBSD nor do I know your system configuration. Pasting the first build failure into a bug report or opening tickets based on an intuition isn't enough.

I offered a way for you to find out, if overriding the compiler solves the problem. But for that you need to checkout the project sources from GitHub and try the above. I even added the two lines of code to master already.

On another note, why do you have GCC on the system? I thought FreeBSD has switched to Clang completely? In that case, I would have expected g++ to be a symlink to clang++. Are you running a non-standard configuration?

It would also be good to know if this problem also applies to other Gems with native extensions, i.e. if this is a generic problem with Ruby on FreeBSD in the _default_ installation.

**Comment by duncan-bayne** [comment]
What I meant by that was: if it _is_ a bug in the Ruby-generated Makefile, it might make more sense for you as the maintainer of the effected gem to open an issue. Otherwise it's some sort of three way game of telephone / psychic debugging. 

Anyway, I opened this issue because I saw an odd behaviour with your gem on my system; I have no need for a fix myself at this point, and thought I'd do you a favour by reporting it rather than just moving on. 

I'll spare myself the irritation next time.
